products = [
    {
        '_id': '30',
        'name': 'PIZZA',
        'image': '/images/pizza.jpg',
        'description':
        'Extra cheese pizzz with garlic',
        'brand': '',
        'category': 'Food',
        'price': 10.50,
        'countInStock': 10,
        'rating': 4.5,
        'numReviews': 0,
    },
    {
        '_id': '31',
        'name': 'BURGER',
        'image': '/images/burger.jpg',
        'description':
        'Introducing the cheese burger with juicy ham',
        'brand': '',
        'category': 'Food',
        'price': 7.14,
        'countInStock': 16,
        'rating': 4.0,
        'numReviews': 8,
    },
    {
        '_id': '32',
        'name': 'SHAWARMA',
        'image': '/images/shawarma.jpg',
        'description':
        'Chicken shawarma',
        'brand': '',
        'category': 'Food',
        'price': 2.00,
        'countInStock': 23,
        'rating': 3,
        'numReviews': 12,
    },
    {
        '_id': '33',
        'name': 'HOT DOG',
        'image': '/images/hot dog.jpg',
        'description':
        'Hot Dog',
        'brand': '',
        'category': 'Food',
        'price': 3.00,
        'countInStock': 61,
        'rating': 5,
        'numReviews': 12,
    },
    {
        '_id': '34',
        'name': 'MEATLOAF',
        'image': '/images/meatloaf.jpg',
        'description':
        'Get a tender and juicy lamb meatloaf',
        'brand': '',
        'category': 'Food',
        'price': 13.99,
        'countInStock': 9,
        'rating': 3.5,
        'numReviews': 10,
    },
    {
        '_id': '35',
        'name': 'ROASTED DUCK',
        'image': '/images/roasted duck.jpg',
        'description':
        'Whole roasted medium rear duck with tender inside',
        'brand': '',
        'category': 'Food',
        'price': 5.00,
        'countInStock': 7,
        'rating': 4,
        'numReviews': 12,   
    },
    {
        '_id': '36',
        'name': 'SPAGETTI',
        'image': '/images/spag and balls.jpg',
        'description':
        'Spaghetti and meat balls',
        'brand': '',
        'category': 'Food',
        'price': 3.00,
        'countInStock': 7,
        'rating': 4,
        'numReviews': 12,   
    },
]   
